### ISSUE TITLE
是不是内置的代理挂了啊

### ISSUE THREAD

**Issue by insoxin** [ifloppy/simpleOnlineCC#1]
Run chmod 777 main
11
[***656] Failed to execute script main
12
Traceback (most recent call last):
13
  File "main.py", line 55, in <module>
14
  File "main.py", line 39, in init
15
  File "requests/api.py", line 76, in get
16
  File "requests/api.py", line 6***, in request
17
  File "requests/sessions.py", line 5***6, in request
18
  File "requests/sessions.py", line 459, in prepare_request
19
  File "requests/models.py", line 3***4, in prepare
20
  File "requests/models.py", line 388, in prepare_url
21
requests.exceptions.MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?
22
Error: Process completed with exit code 255.

**Comment by ifloppy** [comment]
不，我没有设置内置代理，是单IP无限发送请求的

**Comment by insoxin** [comment]
> 不，我没有设置内置代理，是单IP无限发送请求的

那大佬现在试试还正常吗

**Comment by ifloppy** [comment]
青告诉我你设置的最大线程数和设置的代理

**Comment by insoxin** [comment]
> 青告诉我你设置的最大线程数和设置的代理

三个机密，

【可选】一个叫做PROXIY，存放一个URL，访问这个URL会出现HTTP代理，一行一个



这个文档拼写错了  proxy  没有i


同时不设置proxy也会报错,并非可选




另外,我测试自己的机子,没任何流量波动,大佬分享个代理链接?
